import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {pathToFileURL} from 'node:url';
import {resolve} from 'node:path';
await build({entryPoints:['src/chart/LightweightChartsCore.ts'],bundle:true,platform:'node',format:'esm',outfile:'../runtime/node-tests/chart-core.mjs'});
const {LightweightChartsCore,chartTime}=await import(pathToFileURL(resolve('../runtime/node-tests/chart-core.mjs')).href);
const t=1789684920000;
assert.equal(chartTime.toVendor(t),1789684920,'1000-fold timestamp regression');
assert.equal(chartTime.fromVendor(1789684920),t);
assert.throws(()=>chartTime.toVendor(t+.5));
let data=[],updates=[],range=null,crosshair;
const primitives=[];
const series={attachPrimitive:p=>primitives.push(p),setData: v=>data=v,update:(v,historical)=>updates.push({v,historical}),applyOptions:()=>{},priceToCoordinate:p=>p/2};
const scale={subscribeVisibleTimeRangeChange:()=>{},subscribeVisibleLogicalRangeChange:()=>{},setVisibleLogicalRange:()=>{},getVisibleRange:()=>range,setVisibleRange:r=>range=r,timeToCoordinate:t=>t/10};
const chart={addSeries:()=>series,applyOptions:()=>{},timeScale:()=>scale,subscribeCrosshairMove:cb=>crosshair=cb,remove:()=>{}};
globalThis.document={createElement:()=>({style:{},remove:()=>{}})};
globalThis.ResizeObserver=class{observe(){}disconnect(){}};
globalThis.requestAnimationFrame=()=>1;globalThis.cancelAnimationFrame=()=>{};
const core=new LightweightChartsCore(()=>chart);
await core.mount({appendChild:()=>{},querySelectorAll:()=>[]},{theme:'dark'});
assert.equal(primitives.length,2);
assert.equal(primitives[1].paneViews()[0].zOrder(),'normal','FVG background shares the below-candle layer');
await core.setSymbol('XAUUSD','M5');
const bar={tf:'M5',t_open_ms:t,o:4351.22,h:4353.8,l:4350.11,c:4352.64,tick_volume:417,source:'mt5',complete:false,digits:2};
core.applyBars([bar,{...bar,t_open_ms:t+300000}]);
assert.equal(data[0].time,t/1000);
core.setVisibleRange(t,t+300000);assert.deepEqual(core.visibleRange(),{from:t,to:t+300000});
primitives[1].attached({chart,series,requestUpdate:()=>{}});
primitives[1].setLiving({attention_enabled:false,candidates_enabled:false});
const fills=[],strokes=[];
const context={save(){},restore(){},beginPath(){},rect(){},clip(){},setLineDash(){},moveTo(){},lineTo(){},stroke(){},strokeRect:(...v)=>strokes.push(v),fillRect:(...v)=>fills.push(v),createLinearGradient:()=>({addColorStop(){}})};
primitives[1].update([{points:[{t_ms:t-300000,price:100},{t_ms:t,price:104}],style:{token:'zone.fvg'},text_args:{end_ms:t+300000,unfilled_lo:100,unfilled_hi:102,ce:102,direction:'BULLISH'}}]);
primitives[1].paneViews()[0].renderer().drawBackground({useMediaCoordinateSpace:fn=>fn({context,mediaSize:{width:400,height:300}})});
assert.equal(fills.length,1,'a zone anchored before the visible window remains drawn');
assert.equal(fills[0][1],50,'unfilled lower edge');
assert.equal(fills[0][3],1,'rectangle shrinks to unfilled remainder, not original four-point gap');
assert.equal(strokes.length,1,'thin zone border');
assert.equal(core.timeToX(t),t/10000);
assert.equal(core.priceToY(100),50);
const realPerformance=globalThis.performance;let presentationTime=1000;
Object.defineProperty(globalThis,'performance',{value:{now:()=>presentationTime},configurable:true});
const discarded={id:'discarded-zone',points:[{t_ms:t,price:100},{t_ms:t,price:104}],style:{token:'zone.fvg'},text_args:{zone_id:'discarded',tf:'M15',end_ms:t+300000,unfilled_lo:100,unfilled_hi:104,ce:102,direction:'BULLISH',confirmed:false,lifecycle:'DISCARDED',discard_reason:'INVALIDATED',failed_criterion:'GAP_FILLED',decision_id:'discard-1'}};
primitives[1].update([discarded]);
assert.equal(primitives[1].visibleObjects().length,1,'discard survives with living flags disabled');
assert.equal(primitives[1].opacity(discarded),.45,'candidate remains visibly provisional while fading');
primitives[1].update([]);presentationTime+=599;
assert.equal(primitives[1].visibleObjects().length,1,'transport eviction must not interrupt the mandatory fade');
presentationTime+=1;assert.equal(primitives[1].visibleObjects().length,0,'discard is removed only after 600ms');
primitives[1].update([discarded]);assert.equal(primitives[1].visibleObjects().length,0,'repeated snapshots never restart an expired fade');
Object.defineProperty(globalThis,'performance',{value:realPerformance,configurable:true});
let pointed;core.on('crosshair',v=>pointed=v);crosshair({time:t/1000});assert.equal(pointed.t_ms,t);assert.equal(pointed.bar.c,4352.64);
let closes=0;core.on('barclose',()=>closes++);
core.updateBar({...bar,complete:true,c:4352.7});
assert.equal(updates.at(-1).historical,true,'older broker correction must use historical update');
core.updateBar({...bar,complete:true,c:4352.8});assert.equal(closes,1,'close emitted once despite corrections');
assert.throws(()=>core.applyBars([bar,bar]));
core.setSessions([{start_ms:t+60000,end_ms:t+240000,recurring:true}]);
assert.equal(data.filter(v=>v.open===undefined).length,2,'closure has whitespace, never synthetic candles');
core.destroy();
console.log('Chart adapter passed: UTC conversion, range, crosshair, historical corrections, close events, and closure whitespace.');
