import {build} from 'esbuild';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
const bundle=await build({stdin:{contents:"export * from './src/living/Measurement';export * from './src/living/budget';export * from './src/living/SessionScan';export * from './src/living/Camera';export * from './src/living/coverageAudit';",resolveDir:process.cwd()},bundle:true,platform:'node',format:'esm',write:false});
const {MeasurementGesture,VisualBudget,configureBudget,SessionBoundaries,CameraMotion,defaultCamera,readReplayCoverage,coverageAt}=await import(`data:text/javascript;base64,${Buffer.from(bundle.outputFiles[0].text).toString('base64')}`);
configureBudget(12,3);
const decision={seq:1,tf:'M15',object_id:'real-decision',action:'CREATE',source_bars:[1,2,3],measurement:{price_a:30,price_b:33,value:1.75,unit:'R',criterion:'R_GATE'}};
const original=JSON.stringify(decision),gesture=new MeasurementGesture();
gesture.consider([decision],1000,true);
assert.equal(gesture.object(1001,900000).text_args.value,1.75,'use the recorded result rather than recomputing a distance');
assert.deepEqual(gesture.object(1001,900000).points,[{t_ms:900000,price:30},{t_ms:900000,price:33}]);
assert.equal(gesture.object(3499,900000).text_args.opacity,1);
assert.equal(gesture.object(3800,900000).text_args.opacity,.5);
assert.equal(gesture.object(4100,900000),null);
gesture.consider([{...decision,seq:2}],180999,true);assert.equal(gesture.object(180999,900000),null);
gesture.consider([{...decision,seq:3}],181000,true);assert.ok(gesture.object(181000,900000));
const disabled=new MeasurementGesture();disabled.consider([decision],1000,false);assert.equal(disabled.object(1000,900000),null);
assert.equal(JSON.stringify(decision),original,'presentation must not mutate decision geometry or data');
const budget=new VisualBudget(12,3);
assert.equal(budget.admit(Array.from({length:20},(_,i)=>({id:String(i),kind:'draw',duration:450})),0).length,3);
for(let step=1;step<10;step++)budget.admit([{id:`next${step}`,kind:'draw',duration:450}],step*1000);
assert.equal(budget.admit([{id:'over-limit',kind:'call',duration:450}],10000).length,0);
assert.equal(budget.admit([{id:'next-window',kind:'draw',duration:450}],60001).length,1);
for(const [month,hour] of [[0,13],[6,12]]){
 const open=Date.UTC(2026,month,15,hour),calendar=new SessionBoundaries();
 assert.equal(calendar.observe(open-1),null);
 assert.equal(calendar.observe(open).name,'New York','ribbon calendar respects winter/summer New York offsets');
 assert.equal(calendar.observe(open+1),null,'one scan per boundary');
 calendar.observe(open-1);assert.equal(calendar.observe(open),null,'clock reversal cannot repeat a scan');
 const reconnect=new SessionBoundaries();reconnect.observe(open-1000);reconnect.observe(open+1,false);
 assert.equal(reconnect.observe(open+2,true),null,'reconnect never triggers a missed boundary');
 assert.equal(new SessionBoundaries().observe(open+5000),null,'initial load is not a crossing');
}
const camera=new CameraMotion(),range=Object.freeze({from:100,to:200}),beforeRange=JSON.stringify(range);
let cameraState;
for(let frame=0;frame<=600*60;frame++){
 cameraState=camera.step(frame*1000/60,24);
 assert.ok(cameraState.x>=0&&cameraState.x<=24);
 assert.ok(cameraState.scaleY>=.996&&cameraState.scaleY<=1.004);
}
assert.equal(cameraState.x,24);
assert.equal(JSON.stringify(range),beforeRange,'ten-minute camera timeline owns no viewport state');
cameraState=camera.step(600001,2);assert.ok(cameraState.x<=2,'rightmost candle clearance overrides the configured cap');
camera.recentre(600001);assert.equal(camera.step(600701,24).x,0,'promotion recentres over 700ms');
const frozen=camera.step(601001,24,true);assert.deepEqual(camera.step(602001,24,true),frozen,'mandatory fades pause camera decoration');
camera.configure({...defaultCamera,enabled:false});assert.deepEqual(camera.step(603001,24),{x:0,scaleY:1,paused:false});
const reserved=new VisualBudget(12,3);let cancelled=false;
reserved.admit([{id:'motion',kind:'draw',duration:450,cancel:()=>{cancelled=true;}}],0);
reserved.reserve(3,1);assert.ok(cancelled,'mandatory removals can reclaim all motion slots');
const cameraLoop=readFileSync('src/chart/LightweightChartsCore.ts','utf8').split('private cameraLoop(){')[1].split('sessionAt(now:')[0];
assert.ok(!/setVisible|scrollTo|applyOptions|setData|updateBar/.test(cameraLoop),'camera renderer never calls viewport or series setters');
console.log('Living checks passed: measured decision operands, hold/fade, 180-second limit, flags, cadence and concurrency.');
const audit={'metadata.json':JSON.stringify({schema_version:2,offset_s:10,server:'ExnessKE-MT5Trial10'}),'evalpoints.jsonl':[11000,12000,13000].map(t_broker_ms=>JSON.stringify({t_broker_ms,fidelity:'M1'})).join('\n'),'coarse-spans.jsonl':JSON.stringify({state:'SYNTHETIC_COARSE',start_ms:2000,end_ms:3000})};
const coverage=readReplayCoverage(audit);
assert.equal(coverage.from,1000,'coverage uses the recorded broker offset');
assert.equal(coverageAt(coverage,1999),'M1');assert.equal(coverageAt(coverage,2000),'SYNTHETIC_COARSE');assert.equal(coverageAt(coverage,3000),'M1','gap end is exclusive');
assert.throws(()=>readReplayCoverage({...audit,'metadata.json':JSON.stringify({schema_version:1})}),/regenerate/);
assert.throws(()=>readReplayCoverage({...audit,'coarse-spans.jsonl':JSON.stringify({state:'SYNTHETIC_COARSE',start_ms:3000,end_ms:2000})}),/Invalid coarse span/);
console.log('Replay coverage checks passed: amber gap boundaries, broker offset, and schema rejection.');
